module.exports = (sequelize, DataTypes) => {
    return sequelize.define('user', {
        firstname: {type: DataTypes.STRING},
        lastname: {type: DataTypes.STRING},
        kyc: {type: DataTypes.STRING, defaultValue:'unverified'},
        email: {type: DataTypes.STRING},
        image: {type: DataTypes.STRING},
        role: {type: DataTypes.STRING, defaultValue: 'user'},
        balance: {type: DataTypes.FLOAT, defaultValue: 0},
        currency: { type: DataTypes.TEXT, allowNull: true,charset: 'utf8mb4',collate: 'utf8mb4_unicode_ci', },
        dial_code: {type: DataTypes.STRING},
        phone: {type: DataTypes.STRING,allowNull:true},
        password: {type: DataTypes.STRING,allowNull:true},
        reset_code: {type: DataTypes.STRING, allowNull: true},
        status: {type: DataTypes.STRING, defaultValue: 'offline'},
        gender:{type: DataTypes.STRING, allowNull:true},
        verified: {type: DataTypes.STRING, defaultValue: 'false'},
        suspended: {type: DataTypes.STRING, defaultValue: 'false'},
        lastlogin: {type: DataTypes.STRING, allowNull: true},
        account_number: {type: DataTypes.STRING, allowNull: true},
        country: {type: DataTypes.STRING, allowNull: true},
        google: {type: DataTypes.STRING, allowNull: true,defaultValue:'false'},
        state: {type: DataTypes.STRING, allowNull: true},
        debit_card: {type: DataTypes.STRING, allowNull: false,defaultValue:"nil"},
    })
}